import "./globals.css";
import { Inter } from "next/font/google";
import ToastProvider from "./providers/toast.provider";
import "react-toastify/dist/ReactToastify.css";
import UserProvider from "./providers/user.provider";
import { Props } from "@/interfaces/default.interface";
import { useUserContext } from "@/context/userContext";
import ProductProvider from "./providers/product.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>
          <UserProvider>
            <ToastProvider>{children}</ToastProvider>
          </UserProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
