import "./globals.css";
import { Inter } from "next/font/google";
import ToastProvider from "./providers/toast.provider";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "./providers/auth.provider";
import { Props } from "@/interfaces/default";
import { useUserContext } from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ToastProvider>{children}</ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
