import './globals.css';
import { Inter } from 'next/font/google';
import ToastProvider from '../providers/toast.provider';
import 'react-toastify/dist/ReactToastify.css';
import UserProvider from '../providers/user.provider';
import { Props } from '@/interfaces/default.interface';
import ProductProvider from '../providers/product.provider';
import Navbar from '@/components/layouts/navbar';
import Footer from '@/components/layouts/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>
          <UserProvider>
            <ToastProvider>
              <Navbar />
              {children}
              <Footer />
            </ToastProvider>
          </UserProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
